CREATE_USER_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS telegram_users 
        (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER UNIQUE,
        USERNAME CHAR(50),
        FISRT_NAME CHAR(50),
        LAST_NAME CHAR(50),
        UNIQUE (TELEGRAM_ID)
        )
"""

CREATE_BAN_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS ban (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER UNIQUE,
        COUNT INTEGER,
        FOREIGN KEY (TELEGRAM_ID) REFERENCES telegram_users(TELEGRAM_ID)
    )
"""
INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES (?,?,?,?,?)
"""

SELECT_ALL_USERS_QUERY = """
SELECT * FROM telegram_users
"""
SELECT_USER_QUERY = """
SELECT * FROM telegram_users WHERE TELEGRAM_ID = ?
"""
INSERT_BAN_QUERY = """
INSERT OR IGNORE INTO ban VALUES (?,?,?)
"""
UPDATE_BAN_COUNT_QUERY = """
UPDATE ban SET COUNT = COUNT + 1 WHERE TELEGRAM_ID = ?
"""
SELECT_COUNT_QUERY = """SELECT COUNT FROM ban WHERE TELEGRAM_ID = ?"""
